// flow-typed signature: 73f72449e058b9823e389cfe07414e64
// flow-typed version: <<STUB>>/homepage_vfile:../homepage/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'homepage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'homepage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'homepage/build/index' {
  declare module.exports: any;
}

declare module 'homepage/build/static/runtime.bundle' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/babel-plugin-inferno_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/babel-plugin-transform-es2015-modules-commonjs_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/babel-polyfill_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/babel-preset-es2016_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/babel-preset-latest_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/babel-preset-stage-0_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/copy-webpack-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/file-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/in-publish_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/inferno_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/inferno-compat_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/inferno-router_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/jsdom_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/mocha_v3.1.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/styled-components_v2.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/url-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow-typed/npm/webpack-dev-server_vx.x.x' {
  declare module.exports: any;
}

declare module 'homepage/flow/stub/file-loader' {
  declare module.exports: any;
}

declare module 'homepage/flow/stub/raw-loader' {
  declare module.exports: any;
}

declare module 'homepage/src/app' {
  declare module.exports: any;
}

declare module 'homepage/src/components/header' {
  declare module.exports: any;
}

declare module 'homepage/src/components/index' {
  declare module.exports: any;
}

declare module 'homepage/src/components/links' {
  declare module.exports: any;
}

declare module 'homepage/src/components/projects' {
  declare module.exports: any;
}

declare module 'homepage/src/elements/body/body' {
  declare module.exports: any;
}

declare module 'homepage/src/elements/body/index' {
  declare module.exports: any;
}

declare module 'homepage/src/elements/header/image/index' {
  declare module.exports: any;
}

declare module 'homepage/src/elements/header/index' {
  declare module.exports: any;
}

declare module 'homepage/src/elements/header/links/container' {
  declare module.exports: any;
}

declare module 'homepage/src/elements/header/links/icon' {
  declare module.exports: any;
}

declare module 'homepage/src/elements/header/links/index' {
  declare module.exports: any;
}

declare module 'homepage/src/elements/header/links/label' {
  declare module.exports: any;
}

declare module 'homepage/src/elements/header/links/link' {
  declare module.exports: any;
}

declare module 'homepage/src/elements/header/name' {
  declare module.exports: any;
}

declare module 'homepage/src/elements/index' {
  declare module.exports: any;
}

declare module 'homepage/src/elements/project' {
  declare module.exports: any;
}

declare module 'homepage/src/elements/section' {
  declare module.exports: any;
}

declare module 'homepage/src/elements/text/headings' {
  declare module.exports: any;
}

declare module 'homepage/src/elements/text/index' {
  declare module.exports: any;
}

declare module 'homepage/src/elements/text/text' {
  declare module.exports: any;
}

declare module 'homepage/src/index' {
  declare module.exports: any;
}

declare module 'homepage/src/router' {
  declare module.exports: any;
}

declare module 'homepage/src/runtime' {
  declare module.exports: any;
}

declare module 'homepage/src/themes/dark' {
  declare module.exports: any;
}

declare module 'homepage/src/themes/index' {
  declare module.exports: any;
}

declare module 'homepage/test/index' {
  declare module.exports: any;
}

declare module 'homepage/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'homepage/build/index.js' {
  declare module.exports: $Exports<'homepage/build/index'>;
}
declare module 'homepage/build/static/runtime.bundle.js' {
  declare module.exports: $Exports<'homepage/build/static/runtime.bundle'>;
}
declare module 'homepage/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'homepage/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'homepage/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'homepage/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/babel-loader_vx.x.x'>;
}
declare module 'homepage/flow-typed/npm/babel-plugin-inferno_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/babel-plugin-inferno_vx.x.x'>;
}
declare module 'homepage/flow-typed/npm/babel-plugin-transform-es2015-modules-commonjs_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/babel-plugin-transform-es2015-modules-commonjs_vx.x.x'>;
}
declare module 'homepage/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x'>;
}
declare module 'homepage/flow-typed/npm/babel-polyfill_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/babel-polyfill_vx.x.x'>;
}
declare module 'homepage/flow-typed/npm/babel-preset-es2016_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/babel-preset-es2016_vx.x.x'>;
}
declare module 'homepage/flow-typed/npm/babel-preset-latest_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/babel-preset-latest_vx.x.x'>;
}
declare module 'homepage/flow-typed/npm/babel-preset-stage-0_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/babel-preset-stage-0_vx.x.x'>;
}
declare module 'homepage/flow-typed/npm/copy-webpack-plugin_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/copy-webpack-plugin_vx.x.x'>;
}
declare module 'homepage/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'homepage/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'homepage/flow-typed/npm/file-loader_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/file-loader_vx.x.x'>;
}
declare module 'homepage/flow-typed/npm/flow_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/flow_vx.x.x'>;
}
declare module 'homepage/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'homepage/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module 'homepage/flow-typed/npm/in-publish_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/in-publish_vx.x.x'>;
}
declare module 'homepage/flow-typed/npm/inferno_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/inferno_vx.x.x'>;
}
declare module 'homepage/flow-typed/npm/inferno-compat_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/inferno-compat_vx.x.x'>;
}
declare module 'homepage/flow-typed/npm/inferno-router_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/inferno-router_vx.x.x'>;
}
declare module 'homepage/flow-typed/npm/jsdom_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/jsdom_vx.x.x'>;
}
declare module 'homepage/flow-typed/npm/mocha_v3.1.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/mocha_v3.1.x'>;
}
declare module 'homepage/flow-typed/npm/styled-components_v2.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/styled-components_v2.x.x'>;
}
declare module 'homepage/flow-typed/npm/url-loader_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/url-loader_vx.x.x'>;
}
declare module 'homepage/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/webpack_vx.x.x'>;
}
declare module 'homepage/flow-typed/npm/webpack-dev-server_vx.x.x.js' {
  declare module.exports: $Exports<'homepage/flow-typed/npm/webpack-dev-server_vx.x.x'>;
}
declare module 'homepage/flow/stub/file-loader.js' {
  declare module.exports: $Exports<'homepage/flow/stub/file-loader'>;
}
declare module 'homepage/flow/stub/raw-loader.js' {
  declare module.exports: $Exports<'homepage/flow/stub/raw-loader'>;
}
declare module 'homepage/src/app.js' {
  declare module.exports: $Exports<'homepage/src/app'>;
}
declare module 'homepage/src/components/header.js' {
  declare module.exports: $Exports<'homepage/src/components/header'>;
}
declare module 'homepage/src/components/index.js' {
  declare module.exports: $Exports<'homepage/src/components/index'>;
}
declare module 'homepage/src/components/links.js' {
  declare module.exports: $Exports<'homepage/src/components/links'>;
}
declare module 'homepage/src/components/projects.js' {
  declare module.exports: $Exports<'homepage/src/components/projects'>;
}
declare module 'homepage/src/elements/body/body.js' {
  declare module.exports: $Exports<'homepage/src/elements/body/body'>;
}
declare module 'homepage/src/elements/body/index.js' {
  declare module.exports: $Exports<'homepage/src/elements/body/index'>;
}
declare module 'homepage/src/elements/header/image/index.js' {
  declare module.exports: $Exports<'homepage/src/elements/header/image/index'>;
}
declare module 'homepage/src/elements/header/index.js' {
  declare module.exports: $Exports<'homepage/src/elements/header/index'>;
}
declare module 'homepage/src/elements/header/links/container.js' {
  declare module.exports: $Exports<'homepage/src/elements/header/links/container'>;
}
declare module 'homepage/src/elements/header/links/icon.js' {
  declare module.exports: $Exports<'homepage/src/elements/header/links/icon'>;
}
declare module 'homepage/src/elements/header/links/index.js' {
  declare module.exports: $Exports<'homepage/src/elements/header/links/index'>;
}
declare module 'homepage/src/elements/header/links/label.js' {
  declare module.exports: $Exports<'homepage/src/elements/header/links/label'>;
}
declare module 'homepage/src/elements/header/links/link.js' {
  declare module.exports: $Exports<'homepage/src/elements/header/links/link'>;
}
declare module 'homepage/src/elements/header/name.js' {
  declare module.exports: $Exports<'homepage/src/elements/header/name'>;
}
declare module 'homepage/src/elements/index.js' {
  declare module.exports: $Exports<'homepage/src/elements/index'>;
}
declare module 'homepage/src/elements/project.js' {
  declare module.exports: $Exports<'homepage/src/elements/project'>;
}
declare module 'homepage/src/elements/section.js' {
  declare module.exports: $Exports<'homepage/src/elements/section'>;
}
declare module 'homepage/src/elements/text/headings.js' {
  declare module.exports: $Exports<'homepage/src/elements/text/headings'>;
}
declare module 'homepage/src/elements/text/index.js' {
  declare module.exports: $Exports<'homepage/src/elements/text/index'>;
}
declare module 'homepage/src/elements/text/text.js' {
  declare module.exports: $Exports<'homepage/src/elements/text/text'>;
}
declare module 'homepage/src/index.js' {
  declare module.exports: $Exports<'homepage/src/index'>;
}
declare module 'homepage/src/router.js' {
  declare module.exports: $Exports<'homepage/src/router'>;
}
declare module 'homepage/src/runtime.js' {
  declare module.exports: $Exports<'homepage/src/runtime'>;
}
declare module 'homepage/src/themes/dark.js' {
  declare module.exports: $Exports<'homepage/src/themes/dark'>;
}
declare module 'homepage/src/themes/index.js' {
  declare module.exports: $Exports<'homepage/src/themes/index'>;
}
declare module 'homepage/test/index.js' {
  declare module.exports: $Exports<'homepage/test/index'>;
}
declare module 'homepage/webpack.config.js' {
  declare module.exports: $Exports<'homepage/webpack.config'>;
}
